language: generic
os: linux
dist: bionic
notifications:
  email: false

addons:
  apt:
    packages:
      - autoconf
      - pkg-config
      - libtool
      - ninja-build
      - python3-pip
      - python3-setuptools

before_install:
  - sudo pip3 install meson
  - buildscripts/.travis.sh install
script:
  - buildscripts/.travis.sh build

before_cache:
  - find $HOME/.gradle/caches -maxdepth 3 -name '*.lock' -delete
  - rm -rf $HOME/.gradle/caches/journal-1/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
